### PR TITLE
Add missing ground and foot static transforms

### PR DESCRIPTION
**Pull request by aftersomemath**

### CODE REVIEW

**Comment by amiller27** [comment]
I changed the height of base_footprint, looks good otherwise (although the collider mesh is a cylinder, so the feet will probably never actually be on the ground.  Could change it to a convex hull, but I don't really want to do that)

**Comment by aftersomemath** [comment]
I measured that distance using blender as the distance from the origin. Did I make a mistake?

**Comment by amiller27** [comment]
How did you measure it?  I adjusted it so that base_footprint is on the ground when the quad is on the ground

**Comment by aftersomemath** [comment]
I clicked on the bottom of a foot and recorded its xyz position as measured from the origin.

**Comment by amiller27** [comment]
The bottom of the feet is not actually the bottom of the collider

**Comment by aftersomemath** [comment]
I see does this impact my foot measurements as well? They were done in the same manner.

**Comment by amiller27** [comment]
No because they are relative to base_footprint

**Comment by aftersomemath** [comment]
Good to merge then?

**Comment by amiller27** [comment]
Yes

**Review by amiller27 — APPROVED** [review]

**Pull request merged**
